#!/bin/bash
# Derives agent-specific config files from AGENTS.md content.
#
# Supported agents:
#   opencode    — reads AGENTS.md natively; MCP via opencode.json (handled by generate_mcp.sh)
#   claude      — CLAUDE.md wrapper
#   codex       — reads AGENTS.md natively; no extra file needed
#   antigravity — .agent/rules/*.md with activation frontmatter
#   cursor      — .cursor/rules/*.mdc with YAML frontmatter
#   gemini      — GEMINI.md wrapper; MCP via .gemini/settings.json (handled by generate_mcp.sh)

generate_agent_configs() {
    local project_dir="$1"
    local template_dir="$2"
    local agents_tmpl_dir="$template_dir/agents"

    # Set up template vars for agent wrappers
    local type_label
    [ "$PROJECT_TYPE" = "js" ] && type_label="JavaScript / TypeScript (Bun)"
    [ "$PROJECT_TYPE" = "py" ] && type_label="Python (uv)"
    TMPL_VARS[PROJECT_TYPE_LABEL]="$type_label"

    log_step "Generating agent configs"

    # --- OpenCode ---
    # Reads AGENTS.md natively — no wrapper file needed.
    # opencode.json (for MCP) is generated by generate_mcp.sh if any MCPs are enabled.
    if agent_enabled "opencode"; then
        log_ok "opencode (reads AGENTS.md)"
    fi

    # --- Claude Code ---
    if agent_enabled "claude"; then
        render_template "$agents_tmpl_dir/CLAUDE.md.tmpl" "$project_dir/CLAUDE.md"
        log_ok "CLAUDE.md"
    fi

    # --- Codex CLI ---
    # Reads AGENTS.md natively — no wrapper file needed.
    if agent_enabled "codex"; then
        log_ok "codex (reads AGENTS.md)"
    fi

    # --- Antigravity (.agent/rules/*.md) ---
    if agent_enabled "antigravity"; then
        generate_antigravity_rules "$project_dir" "$template_dir"
        log_ok ".agent/rules/"
    fi

    # --- Cursor (.cursor/rules/*.mdc) ---
    if agent_enabled "cursor"; then
        generate_cursor_rules "$project_dir" "$template_dir"
        log_ok ".cursor/rules/"
    fi

    # --- Gemini CLI ---
    # GEMINI.md wrapper; MCP via .gemini/settings.json (handled by generate_mcp.sh).
    if agent_enabled "gemini"; then
        render_template "$agents_tmpl_dir/GEMINI.md.tmpl" "$project_dir/GEMINI.md"
        log_ok "GEMINI.md"
    fi
}

# --- Antigravity: split rules into .agent/rules/*.md with activation frontmatter ---
generate_antigravity_rules() {
    local project_dir="$1"
    local template_dir="$2"
    local rules_dir="$template_dir/rules"
    local out_dir="$project_dir/.agent/rules"
    ensure_dir "$out_dir"

    write_antigravity_rule "$rules_dir/coding-style.md" "$out_dir/01-coding-style.md"
    write_antigravity_rule "$rules_dir/testing.md"      "$out_dir/02-testing.md"
    write_antigravity_rule "$rules_dir/version-control.md" "$out_dir/03-version-control.md"
    write_antigravity_rule "$rules_dir/debugging.md"    "$out_dir/04-debugging.md"
    write_antigravity_rule "$rules_dir/task-management.md" "$out_dir/05-task-management.md"
    write_antigravity_rule "$rules_dir/code-organization.md" "$out_dir/06-code-organization.md"

    if [ "$PROJECT_TYPE" = "js" ]; then
        write_antigravity_rule "$rules_dir/tooling-js.md" "$out_dir/07-tooling.md"
    elif [ "$PROJECT_TYPE" = "py" ]; then
        write_antigravity_rule "$rules_dir/tooling-py.md" "$out_dir/07-tooling.md"
    fi
}

write_antigravity_rule() {
    local src="$1" dst="$2"
    if [ ! -f "$src" ]; then return; fi

    local content
    content=$(<"$src")
    content="$(process_conditionals "$content")"
    content="$(substitute_vars "$content")"

    {
        echo "---"
        echo "activation: always_on"
        echo "---"
        echo ""
        echo "$content"
    } > "$dst"
}

# --- Cursor: split rules into .mdc files with YAML frontmatter ---
generate_cursor_rules() {
    local project_dir="$1"
    local template_dir="$2"
    local rules_dir="$template_dir/rules"
    local out_dir="$project_dir/.cursor/rules"
    ensure_dir "$out_dir"

    write_cursor_rule "$rules_dir/coding-style.md" "$out_dir/coding-style.mdc" \
        "Code style, naming, and design guidelines" "**" "true"

    write_cursor_rule "$rules_dir/testing.md" "$out_dir/testing.mdc" \
        "Testing philosophy and requirements" "**/*.test.*,**/*.spec.*,**/tests/**" "true"

    write_cursor_rule "$rules_dir/version-control.md" "$out_dir/version-control.mdc" \
        "Version control and commit conventions" "**" "true"

    if [ "$PROJECT_TYPE" = "js" ]; then
        write_cursor_rule "$rules_dir/tooling-js.md" "$out_dir/tooling.mdc" \
            "JavaScript/TypeScript tooling and commands" "**/*.ts,**/*.js,**/*.tsx,**/*.jsx" "true"
    elif [ "$PROJECT_TYPE" = "py" ]; then
        write_cursor_rule "$rules_dir/tooling-py.md" "$out_dir/tooling.mdc" \
            "Python tooling and commands" "**/*.py" "true"
    fi
}

write_cursor_rule() {
    local src="$1" dst="$2" description="$3" globs="$4" always_apply="$5"

    if [ ! -f "$src" ]; then return; fi

    local content
    content=$(<"$src")
    content="$(process_conditionals "$content")"
    content="$(substitute_vars "$content")"

    {
        echo "---"
        echo "description: \"$description\""
        echo "globs: \"$globs\""
        echo "alwaysApply: $always_apply"
        echo "---"
        echo ""
        echo "$content"
    } > "$dst"
}

# Helper: process a rule file (conditionals + vars) and write to destination
write_processed_rule() {
    local src="$1" dst="$2"
    if [ ! -f "$src" ]; then return; fi

    local content
    content=$(<"$src")
    content="$(process_conditionals "$content")"
    content="$(substitute_vars "$content")"
    echo "$content" > "$dst"
}
